#!/bin/sh

# TODO 路由表

: '
网络附加存储（NAS）
--ftp(vsftpd)  770934750
--SMB/CIFS  327613435
--NFS
--iSCSI Target  643911329
--WebDAV
--KODExplorer
--DLNA  111130352
--缓存代理  151034078
网站
--nginx  576758378
--PHP  576758378
--MySQL  496962172
其它
--ngrokc  321256294
--VPN  937247062
--DNS

https://app.hiwifi.com/plugin?sid=13
https://app.hiwifi.com/store.php?m=plugins&a=info&rid=r73855926759&sid=327613435
'

controller_path=/usr/lib/lua/luci/controller/admin_web/cp.lua
view_cp_path=/usr/lib/lua/luci/view/admin_web/cp.htm
view_cp_monitor_path=/usr/lib/lua/luci/view/admin_web/cp_monitor.htm
view_cp_tools_path=/usr/lib/lua/luci/view/admin_web/cp_tools.htm
view_cp_function_path=/usr/lib/lua/luci/view/admin_web/cp_function.htm
sh_path=/etc/market/cp.sh
sh_log_path=/etc/market/cp-log.lua
daemon_path=/etc/init.d/hiwifi_control_panel

mem_opt_path=/etc/rc.d/S99cp_mem_opt
ping_opt_path=/etc/rc.d/S99cp_ping_opt

samba_opt_on(){
    sed -i 's/SO_RCVBUF=[0-9]*/SO_RCVBUF=655360/g' /etc/samba/smb.conf.template
    sed -i 's/SO_SNDBUF=[0-9]*/SO_SNDBUF=655360/g' /etc/samba/smb.conf.template
    /etc/init.d/samba reload
}

samba_opt_off(){
    sed -i 's/SO_RCVBUF=[0-9]*/SO_RCVBUF=65535/g' /etc/samba/smb.conf.template
    sed -i 's/SO_SNDBUF=[0-9]*/SO_SNDBUF=65535/g' /etc/samba/smb.conf.template
    /etc/init.d/samba reload
}

samba_opt_status(){
    status_1=$(cat /var/etc/smb.conf | grep "SO_RCVBUF=655360 SO_SNDBUF=655360" | wc -l)
    if [ $status_1 -ge "1" ]; then
        echo "打开"
    else
        echo "关闭"
    fi
}

samba_opt_switch(){
    if [ $(samba_opt_status) = "打开" ]; then
        samba_opt_off
    else
        samba_opt_on
    fi
    echo $(samba_opt_status)
}

mem_opt_on(){
    echo 2048 > /proc/sys/vm/min_free_kbytes
    echo 50 > /proc/sys/vm/vfs_cache_pressure
    (
    cat <<EOF
#!/bin/sh /etc/rc.common

START=99

start(){
    (sleep 10; echo 2048 > /proc/sys/vm/min_free_kbytes)&
    echo 50 > /proc/sys/vm/vfs_cache_pressure
}
EOF
    ) > $mem_opt_path
    chmod 777 $mem_opt_path
}

mem_opt_off(){
    rm $mem_opt_path
    echo 2049 > /proc/sys/vm/min_free_kbytes
    echo 200 > /proc/sys/vm/vfs_cache_pressure
}

mem_opt_status(){
    status_1=$(cat /proc/sys/vm/min_free_kbytes)
    if [ $status_1 -le "2048" ]; then
        echo "打开"
    else
        echo "关闭"
    fi
}

mem_opt_switch(){
    if [ $(mem_opt_status) = "打开" ]; then
        mem_opt_off
    else
        mem_opt_on
    fi
    echo $(mem_opt_status)
}

ping_opt_on(){
    echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
    (
    cat <<EOF
#!/bin/sh /etc/rc.common

START=99

start(){
    echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
}
EOF
    ) > $ping_opt_path
    chmod 777 $ping_opt_path
}

ping_opt_off(){
    rm $ping_opt_path
    echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_all
}

ping_opt_status(){
    status_1=$(cat /proc/sys/net/ipv4/icmp_echo_ignore_all)
    if [ $status_1 -eq "1" ]; then
        echo "打开"
    else
        echo "关闭"
    fi
}

ping_opt_switch(){
    if [ $(ping_opt_status) = "打开" ]; then
        ping_opt_off
    else
        ping_opt_on
    fi
    echo $(ping_opt_status)
}




update_res(){
    stop
    rm $controller_path
    rm $view_cp_path
    rm $view_cp_monitor_path
    rm $view_cp_tools_path
    rm $view_cp_function_path
    rm $sh_path
    rm $sh_log_path
    rm $daemon_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp.htm -O $view_cp_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp_monitor.htm -O $view_cp_monitor_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp_tools.htm -O $view_cp_tools_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp_function.htm -O $view_cp_function_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp.lua -O $controller_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp.sh -O $sh_path
    wget http://139.129.20.107/hiwifi_contorl_panel/cp-log.lua -O $sh_log_path
    wget http://139.129.20.107/hiwifi_contorl_panel/hiwifi_control_panel -O $daemon_path
    chmod +x $daemon_path
    rm /var/run/luci-indexcache
    start
}

install(){
    cp hiwifi_control_panel /etc/init.d
    chmod +x /etc/init.d/hiwifi_control_panel
    cp cp.lua $controller_path
    cp cp.htm $view_cp_path
    cp cp_monitor.htm $view_cp_monitor_path
    cp cp_tools.htm $view_cp_tools_path
    cp cp_function.htm $view_cp_function_path
    cp cp.sh $sh_path
    cp cp-log.lua $sh_log_path
    cp -r cp /www
    rm /var/run/luci-indexcache
    start
    sed -i 's/<span class="ft-nav">/<span class="ft-nav"><a href="..\/cp" target="_blank">服务器控制面板<\/a><span>\&nbsp;\&nbsp;<\/span>\|<span>\&nbsp;\&nbsp;<\/span>/g' /usr/lib/lua/luci/view/admin_web/footer.htm
}

uninstall(){
    stop
    rm $controller_path
    rm $view_cp_path
    rm $view_cp_monitor_path
    rm $view_cp_tools_path
    rm $view_cp_function_path
    rm $sh_path
    rm $sh_log_path
    rm $daemon_path
    rm -r /www/cp
    sed -i 's/<span class="ft-nav"><a href="..\/cp" target="_blank">服务器控制面板<\/a><span>\&nbsp;\&nbsp;<\/span>|<span>\&nbsp;\&nbsp;<\/span>/<span class="ft-nav">/g' /usr/lib/lua/luci/view/admin_web/footer.htm
    return 0
}

start() {
    # 开始记录状态历史
    /etc/init.d/hiwifi_control_panel start
    /etc/init.d/hiwifi_control_panel enable
	return 0
}

stop() {
    # 停止记录状态历史
    /etc/init.d/hiwifi_control_panel stop
    /etc/init.d/hiwifi_control_panel disable
	return 0
}

status() {
    lan_ip=$(ifconfig br-lan|grep 'inet addr'|awk '{print $2}'|tr -d 'addr:')
    if [ $(ps|grep 'cp.sh'|wc -l) -ge "2" ]; then
        echo '{ "status" : "running", "msg" : "监控功能已启动。<br>点击打开控制面板： <a href=\"http://'$lan_ip'/cgi-bin/turbo/cp\" target=\"_blank\">http://'$lan_ip'/cgi-bin/turbo/cp</a>" }'
    else
        echo '{ "status" : "stopped", "msg" : "监控功能未启动。<br>点击打开控制面板： <a href=\"http://'$lan_ip'/cgi-bin/turbo/cp\" target=\"_blank\">http://'$lan_ip'/cgi-bin/turbo/cp</a>" }'
    fi
}
