#!/bin/sh

# TODO 路由表

: '
网络附加存储（NAS）
--ftp(vsftpd)  770934750
--SMB/CIFS  327613435
--NFS
--iSCSI Target  643911329
--WebDAV
--KODExplorer
--DLNA  111130352
--缓存代理  151034078
网站
--nginx  576758378
--PHP  576758378
--MySQL  496962172
其它
--ngrokc  321256294
--VPN  937247062
--DNS

https://app.hiwifi.com/plugin?sid=13
https://app.hiwifi.com/store.php?m=plugins&a=info&rid=r73855926759&sid=327613435
'

install(){
    . cp2.sh 
    install_cp
}

uninstall(){
    . /etc/market/cp2.sh
    uninstall_cp
}

start() {
    # 开始记录状态历史
    . /etc/market/cp2.sh
    start_cp
	return 0
}

stop() {
    # 停止记录状态历史
    . /etc/market/cp2.sh
    stop_cp
	return 0
}

status() {
    . /etc/market/cp2.sh
    status_cp
}
